version: "2"
linters:
  settings:
    errcheck:
      exclude-functions:
        - (io.Closer).Close
        - (*database/sql.Rows).Close
        - (*database/sql.Stmt).Close
        - fmt.Fprint
        - fmt.Fprintf
        - fmt.Fprintln
