services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "15432:5432"
    environment:
      POSTGRES_DB: silkstrand
      POSTGRES_USER: silkstrand
      POSTGRES_PASSWORD: localdev
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U silkstrand"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "16379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres-backoffice:
    image: postgres:16-alpine
    ports:
      - "15433:5432"
    environment:
      POSTGRES_DB: silkstrand_backoffice
      POSTGRES_USER: silkstrand
      POSTGRES_PASSWORD: localdev
    volumes:
      - pgdata-backoffice:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U silkstrand"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
  pgdata-backoffice:
