DROP TABLE IF EXISTS scan_results;
DROP TABLE IF EXISTS scans;
DROP TABLE IF EXISTS bundles;
DROP TABLE IF EXISTS credentials;
DROP TABLE IF EXISTS targets;
DROP TABLE IF EXISTS agents;
DROP TABLE IF EXISTS tenants;
DROP EXTENSION IF EXISTS "uuid-ossp";
