package recon

// PDTool is one ProjectDiscovery binary tracked for runtime install
// (ADR 003 R1a). Pins are populated in PR #6 (infra/seed-pd-binaries)
// once the silkstrand-runtimes bucket has objects.
type PDTool struct {
	Name    string                       // "naabu" | "httpx" | "nuclei"
	Version string                       // upstream semver
	SHA256  map[string]string            // platform key (e.g. "linux-amd64") → hex sha256
}

// pdTools is the compile-time pin table. Generated by the
// release-pd-tools workflow. Bumping a tool: re-run the workflow with
// the new tag and paste the snippet from its log.
//
// Keys in SHA256 are "<os>-<arch>" matching runtime.GOOS + "-" +
// runtime.GOARCH; values are lowercase hex.
var pdTools = []PDTool{
	{
		Name:    "naabu",
		Version: "2.5.0",
		SHA256: map[string]string{
			"linux-amd64":   "d97cad03dd94c68d0bb0495d2f5da3ada7a0a01eed8df24e3d51dc265547dd2d",
			"linux-arm64":   "3d15d5edfc4eeea3fdb25004f4bceb464c96c90e8a5d0daa9b0f72d38763fbc7",
			"darwin-amd64":  "17a065548e213096698fc4458b16d68144a49e65666d99cc086eb93eb05fab0e",
			"darwin-arm64":  "36ee9629079fa59ac6d93c5328976d39fbd4f1cc84b2d64a94a0f526a4b28b48",
			"windows-amd64": "25934ec95ede3fc3750b26b0095d7838f0c3e5042c10d3e5e0cfa68e94acef19",
		},
	},
	{
		Name:    "httpx",
		Version: "1.9.0",
		SHA256: map[string]string{
			"linux-amd64":   "3c7012a0acba4ea9bfa8947e2c4799f750aba0b0ae8ecc7bc090a1be26af2ce7",
			"linux-arm64":   "ce58c610e2c0cf48770f058c37b4db4b9c45c2ecb59ad66ce8f80092c4fd9904",
			"darwin-amd64":  "c4a17f1bdf97c96d761705ef05d77d37b451a273a63bb15726975c787d29f89c",
			"darwin-arm64":  "24b233307212f6f0d1077940bd662dc160a32976980e2941ce837c4666719ece",
			"windows-amd64": "388dbc5e22391e49018227b05d1f4a45bb4cb403be02fd4711e3d7ee8557c2f7",
		},
	},
	{
		Name:    "nuclei",
		Version: "3.7.1",
		SHA256: map[string]string{
			"linux-amd64":   "4f006f97fe44993e1b17627a3b318ade96fd1f51e9517355cfe30f86c94679a0",
			"linux-arm64":   "f67dc5984372eb1342a2f13692330f2db72c6fcbdc9071174d4ce9bf7b60fc2e",
			"darwin-amd64":  "54ae9456b8221b74274a7fe96738816ba45008b7c209431c3bba855a05c9a7d9",
			"darwin-arm64":  "2742271da1ad8460a32df68eda10a7e4d15fc9193cab056fabb32155354f2ae6",
			"windows-amd64": "77d76e3e8fd312314cd0fe45f40122d7689c5b2bef8cbc457c5d3c1515e958cd",
		},
	},
}

// nucleiTemplatesPin pins the SilkStrand-curated template tarball.
// Version is a SilkStrand semver, not upstream. Bumping: re-run the
// release-pd-tools workflow with a new templates_version input.
var nucleiTemplatesPin = struct {
	Version string // SilkStrand semver
	SHA256  string // hex of the .tar.gz
}{
	Version: "0.1.0",
	SHA256:  "ec745effc53918c9f405bd62486bea9a1e30543fd92f24802cad6dbba00c4d96",
}
